### PR TITLE
Post hackathon changes

### PR DESCRIPTION
**Pull request by neilo40**
Hi Jeff,

I raise this purely out of courtesy.  There are some major changes, so I will take no offense if you don't want to merge it :-)

Just wanted to say a big thanks for this BTW, we took it to the Glasgow Uni [hackathon](https://gutechsoc.com/hackathon) last month and it was hugely popular.  We had about 60 students tackle it with varying degrees of success

The winning entry completing E1M1: https://youtu.be/xkUHqYx71b8

I also made a bot: https://github.com/neilo40/doom-bot.  There's a couple of videos there of it completing E1M1 and E1M2.  E1M3 starts to get a bit tricky.  We may have to add an endpoint for the state of movable sectors (e.g. staircases).  A few others from the office also gave it a shot, so we had a real smorgasbord of attempts, in python, java, scala, c#, c, perl and even powershell of all things!

I'm hoping to take it to Edinburgh University's [hackathon](http://2017.hacktheburgh.com/) next spring too :-)  

## Changes:

* Removed all the threading code.  You were right to be skeptical.  Turns out Virtualbox's port forwarding was adding ~500ms to each request. Running native absolutely didn't need this.
* Added a new method for turning quickly and accurately.  I added this one during the event (with some fixes after I got some sleep).  Turns out it's pretty much impossible to create a functioning bot with the keypress, check angle, keypress, check angle approach
* Made a number of endpoints "restricted", i.e. can only be run by the server player.  Pretty much essential for a competitive deathmatch.  Single player is unaffected - all endpoints available.
* Added methods for checking line-of-sight and testing whether player can move to (x,y)
* Updated RAML to reflect all new/changed endpoints
* Added a bunch of checks to avoid players accidentally crashing their engine.

Thanks again for an awesome project!

### CODE REVIEW

**Comment by jeff-1amstudios** [comment]
@neilo40 thanks very much for the patch! I checked out a couple of the videos of the bots, was very impressed! I'll look through this changeset this week and get it merged. I think it pretty much all makes sense from what I've scanned :)

**Comment by ZacharieGignac** [comment]
will it merge after 5 years?!

**Comment by mashaal** [comment]
> will it merge after 5 years?!

Doesn't look like it!

**Comment by jeff-1amstudios** [comment]
Not after 5 years, but definitely after 7 it is time to merge!

**Pull request merged**
